version: '3.4'

services:
  tfgdb:
    container_name: tfgdb
    restart: always
    ports: 
      - 27028:27017
    volumes:
      - tfg_mongo_data:/data/db
  
  tfgapi:
    container_name: tfg.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings__ConnectionString=mongodb://tfgdb
      - DatabaseSettings__DatabaseName=CustomerDb
      - DatabaseSettings__CustomerCollectionName=Customers
      - DatabaseSettings__RoleCollectionName=Roles
      - jwtSecret=my_secret_key_12345
      - jwtExpiry=3600
      - baseUrl=http://localhost:5001
    depends_on:
      - tfgdb
    ports:
      - 5001:80